import tiposDeSimbolos from '../tipos-de-simbolos/lexico-regular';

export const palavrasReservadas = {
    biblioteca: tiposDeSimbolos.BIBLIOTECA,
    cadeia: tiposDeSimbolos.CADEIA,
    caracter: tiposDeSimbolos.CARACTER,
    caso: tiposDeSimbolos.CASO,
    const: tiposDeSimbolos.CONSTANTE,
    contrario: tiposDeSimbolos.CONTRARIO,
    enquanto: tiposDeSimbolos.ENQUANTO,
    escolha: tiposDeSimbolos.ESCOLHA,
    escreva: tiposDeSimbolos.ESCREVA,
    e: tiposDeSimbolos.E,
    faca: tiposDeSimbolos.FACA,
    falso: tiposDeSimbolos.FALSO,
    funcao: tiposDeSimbolos.FUNCAO,
    inclua: tiposDeSimbolos.INCLUA,
    inteiro: tiposDeSimbolos.INTEIRO,
    leia: tiposDeSimbolos.LEIA,
    limpa: tiposDeSimbolos.LIMPA,
    logico: tiposDeSimbolos.LOGICO,
    nao: tiposDeSimbolos.NEGACAO,
    ou: tiposDeSimbolos.OU,
    para: tiposDeSimbolos.PARA,
    pare: tiposDeSimbolos.PARE,
    programa: tiposDeSimbolos.PROGRAMA,
    real: tiposDeSimbolos.REAL,
    retorne: tiposDeSimbolos.RETORNE,
    se: tiposDeSimbolos.SE,
    senao: tiposDeSimbolos.SENAO,
    vazio: tiposDeSimbolos.VAZIO,
    verdadeiro: tiposDeSimbolos.VERDADEIRO,
};
